# Generated by Django 3.2 on 2023-02-24 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('content', models.TextField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('entry_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='type', to='forum.entrytype')),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
    ]
