# Generated by Django 3.2 on 2023-03-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_response_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='author',
            field=models.CharField(max_length=60),
        ),
    ]
