# Generated by Django 5.1.5 on 2025-01-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
