# Generated by Django 5.1.5 on 2025-01-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0002_veterinary_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinary',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
